version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bookyourshow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookyourshow
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: bookyourshow_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: bookyourshow_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
